# To learn more about the skaffold.yaml schema visit
# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2beta19
kind: Config
build:
  tagPolicy:
    sha256: {}
  googleCloudBuild:
    diskSizeGb: 100
    machineType: N1_HIGHCPU_8
    timeout: 900s
  artifacts:
  - context: src/
    image: asia-east1-docker.pkg.dev/shawn-demo-2022/image-repos/hello-demo
deploy:
  kustomize:
    paths:
    - kubernetes-manifests/dev
  kubeContext: gke_shawn-demo-2022_asia-east1-a_production
profiles:
- name: dev
  deploy:
    kustomize:
      paths:
      - kubernetes-manifests/dev
    kubeContext: gke_shawn-demo-2022_asia-east1-a_production
- name: uat
  deploy:
    kustomize:
      paths:
      - kubernetes-manifests/uat
    kubeContext: gke_shawn-demo-2022_asia-east1-a_production
- name: production
  deploy:
    kustomize:
      paths:
      - kubernetes-manifests/production
    kubeContext: gke_shawn-demo-2022_asia-east1-a_production
