steps:
- id: 'buildImage'
  name: 'gcr.io/k8s-skaffold/skaffold:v1.35.1'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    skaffold build --file-output tags.json
- id: 'Deploy Istio Gateway and Certificate'
  name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run 
  - --filename=kubernetes-manifests/gateway/
  - --location=asia-east1-a
  - --cluster=production
- id: 'cloudDeploy'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: sh
  args:
  - '-c'
  - |
    if [ -f tags.json ]; then
      gcloud beta deploy releases create rev-${SHORT_SHA} \
      --delivery-pipeline=${_PIPELINE} \
      --labels=version=${SHORT_SHA} \
      --region ${_LOCATION} \
      --build-artifacts tags.json
    else 
      echo "tags.json does not exist"
    fi
  waitFor:
    - buildImage
# Add more power, and more time, for heavy Skaffold build
timeout: '3600s'
options:
  machineType: 'N1_HIGHCPU_8'
substitutions:
  _LOCATION: 'asia-east1'
  _PIPELINE: 'hello-demo'