steps:
- id: 'buildImage'
  name: 'gcr.io/k8s-skaffold/skaffold:v1.35.1'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    skaffold build --file-output tags.json
- id: 'cloudDeploy'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: sh
  args:
  - '-c'
  - |
    gcloud beta deploy \
    releases create rev-${SHORT_SHA} \
    --delivery-pipeline=hipster \
    --labels=version=${SHORT_SHA} \
    --region ${_LOCATION} \
    --build-artifacts tags.json
  waitFor:
    - buildImage
# Add more power, and more time, for heavy Skaffold build
timeout: '3600s'
options:
  machineType: 'N1_HIGHCPU_8'
substitutions:
  _LOCATION: asia-east1%