apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hello-uat
spec:
  # The secret name to store the signed certificate
  secretName: hello-uat-cert-tls
  # Common Name
  commonName: hello-uat.shawnk8s.com
  isCA: false
  # DNS SAN
  dnsNames:
    - hello-uat.shawnk8s.com
  # Duration of the certificate
  duration: 8760h
  # Renew 8 hours before the certificate expiration
  renewBefore: 360h
  # Important: Ensure the issuerRef is set to the issuer or cluster issuer configured earlier
  issuerRef:
    group: cas-issuer.jetstack.io
    kind: GoogleCASClusterIssuer # or GoogleCASIssuer
    name: cas-cluster-issuer