apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: my-frontend-config 
spec:
  sslPolicy: "hello-ssl-policy"
  redirectToHttps:
    enabled: true
    responseCodeName: "301"
